### ISSUE TITLE
Conceptualisation 🖊️ Code of Hammurabi

### ISSUE THREAD

**Issue by Ismael-KG** [Ismael-KG/A-History-of-Research-Ethics#111]
### Title

Code of Hammurabi

### Date or Period 📅

1755 BCE, not to say 'some time between 2342 and 1950 BCE,' although that's how divergent the views are (Souvay, [1910](https://www.newadvent.org/cathen/07125a.htm)).

### Intro

An ancient legal text that makes reference to the punishment of physicians who harm their patients.

**This story has been published [on Tiki-Toki](https://www.tiki-toki.com/timeline/entry/1753034/A-History-of-Research-Ethics/#vars!panel=16462371!), but please feel free to reopen this issue and make any suggestions below!**

**Comment by GeorgiaHCA** [comment]
#142

**Comment by alejandro-deltell** [comment]
#142
