### ISSUE TITLE
Conceptualisation 🖊️ Concerning the Diseases of Women, by Metrodora

### ISSUE THREAD

**Issue by Ismael-KG** [Ismael-KG/A-History-of-Research-Ethics#115]
### Title

Concerning the Diseases of Women, by Metrodora

### Date or Period 📅

200 CE because she seems to have lived in the second century (Gregory et al., [2013](https://doi.org/10.1177/1553350613485304)).

### Intro

Metrodora appears to be the first female author of a medical text.

**This story has been published [on Tiki-Toki](https://www.tiki-toki.com/timeline/entry/1753034/A-History-of-Research-Ethics/#vars!panel=16507868!), but please feel free to reopen this issue and make any suggestions below!**

**Comment by ninadicara** [comment]
#142 :)
