### ISSUE TITLE
Conceptualisation 🖊️ Ge Hong & Bao Gu

### ISSUE THREAD

**Issue by Ismael-KG** [Ismael-KG/A-History-of-Research-Ethics#117]
### Title

Ge Hong & Bao Gu

### Date or Period 📅

340 (Hsu, [2006](https://doi.org/10.1111/j.1365-2125.2006.02673.x)).

### Intro

Ge Hong reconciles Confucianism and Daoism, leaves instructions for a 2015 Nobel Prize winner, and records Bao Gu's techniques in moxibustion.

**This story has been published [on Tiki-Toki](https://www.tiki-toki.com/timeline/entry/1753034/A-History-of-Research-Ethics/#vars!panel=16623258!), but please feel free to reopen this issue and make any suggestions below!**

**Comment by sezezulka** [comment]
#142
