### ISSUE TITLE
Conceptualisation 🖊️ Royal Society

### ISSUE THREAD

**Issue by Ismael-KG** [Ismael-KG/A-History-of-Research-Ethics#120]
### Title

Royal Society

### Date or Period 📅

1660 (Royal Society, [n.d.](https://royalsociety.org/about-us/history/)).

### Intro

The Royal Society is established in London, England.

**This story has been published [on Tiki-Toki](https://www.tiki-toki.com/timeline/entry/1753034/A-History-of-Research-Ethics/#vars!date=1547_BC-08-02_11:24:45!), but please feel free to reopen this issue and make any suggestions below!**

**Comment by EstherPlomp** [comment]
#142

**Comment by pherterich** [comment]
#142
