### ISSUE TITLE
Conceptualisation 🖊️ Princess Dashkova directs the Petersburg Academy of Arts and Sciences

### ISSUE THREAD

**Issue by Ismael-KG** [Ismael-KG/A-History-of-Research-Ethics#123]
### Title

Princess Dashkova directs the Petersburg Academy of Arts and Sciences

### Date or Period 📅

1782 (The Editors of Encyclopaedia Britannica, [2021](https://www.britannica.com/biography/Yekaterina-Romanovna-Vorontsova-Knyaginya-Dashkova)).

### Intro

Princess Dashkova Yekaterina Romanovna Vorontsova is appointed to direct the Petersburg Academy of Arts and Sciences, establishes the Russian Academy, and helps reflect on gender stereotypes and allyship.

**This story has been published [on Tiki-Toki](https://www.tiki-toki.com/timeline/entry/1753034/A-History-of-Research-Ethics/#vars!panel=16575859!), but please feel free to reopen this issue and make any suggestions below!**

**Comment by BrainonSilicon** [comment]
I would love to make some edits to this file https://github.com/Ismael-KG/An_Incomplete_History_of_Research_Ethics/issues/123#issue-1089868668

**Comment by Ismael-KG** [comment]
Good effort, @BrainonSilicon, haha. Thank you for joining for the session! (#142)
